name: Routeincome
options:
  bundleIdPrefix: com.shimondeitel.vendingroute
  deploymentTarget:
    iOS: "17.0"
  createIntermediateGroups: true
  groupSortPosition: top
settings:
  base:
    MARKETING_VERSION: "1.0"
    CURRENT_PROJECT_VERSION: "1"
    SWIFT_VERSION: "5.0"
    DEVELOPMENT_TEAM: "W7Q885Q59C"
    CODE_SIGN_STYLE: Automatic
    IPHONEOS_DEPLOYMENT_TARGET: "17.0"
    TARGETED_DEVICE_FAMILY: "1"
    ENABLE_USER_SCRIPT_SANDBOXING: "YES"
targets:
  Routeincome:
    type: application
    platform: iOS
    sources:
      - path: Routeincome
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.shimondeitel.vendingroute
        TARGETED_DEVICE_FAMILY: "1"
        INFOPLIST_FILE: Routeincome/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        ENABLE_PREVIEWS: "YES"
        GENERATE_INFOPLIST_FILE: "NO"
  RouteincomeTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: RouteincomeTests
      - path: Routeincome.storekit
    dependencies:
      - target: Routeincome
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.shimondeitel.vendingroute.tests
        GENERATE_INFOPLIST_FILE: "YES"
        TARGETED_DEVICE_FAMILY: "1"
  RouteincomeUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: RouteincomeUITests
    dependencies:
      - target: Routeincome
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.shimondeitel.vendingroute.uitests
        GENERATE_INFOPLIST_FILE: "YES"
        TARGETED_DEVICE_FAMILY: "1"
schemes:
  Routeincome:
    build:
      targets:
        Routeincome: all
        RouteincomeTests: [test]
        RouteincomeUITests: [test]
    run:
      config: Debug
      storeKitConfiguration: Routeincome.storekit
    test:
      config: Debug
      storeKitConfiguration: Routeincome.storekit
      targets:
        - RouteincomeTests
        - RouteincomeUITests
    archive:
      config: Release
